//! Codegen: run the lifter on each of the 12 step-circuit fixtures
//! and emit:
//!   * the prover `ProverKernel` impl
//!   * the verifier `VerifierKernel` impl
//!   * the `ConstraintDef` bundle binding the two kernels
//!
//! All into a single `gen_kernels.rs` file in `OUT_DIR`. The crate
//! `include!`s that file under `gen_kernels` (gated on the `fixture`
//! feature). `fixture::*` re-exports the ConstraintDef bundles under
//! shorter names.

use std::{env, fs, path::Path};

use mpz_circuits_new::fixtures;
use mpz_fields::{gf2::Gf2, gf2_64::Gf2_64};
use mpz_poly_proof_lifter::{
    LifterError, Paths, emit_constraint_def, emit_prover, emit_verifier, trace_constraint,
};

fn main() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest = Path::new(&out_dir).join("gen_kernels.rs");

    // Inside `mpz-poly-proof-core`, the generated code lives in the
    // `gen_kernels` module — `crate::...` paths resolve. The lifter's
    // default `Paths` uses external absolute paths; override here.
    let paths = Paths {
        kernel: "crate::kernel::ProverKernel".into(),
        verifier_kernel: "crate::kernel::VerifierKernel".into(),
        constraint_def: "crate::kernel::ConstraintDef".into(),
        extension_field: "crate::ExtensionField".into(),
        field: "crate::Field".into(),
    };

    let mut source = String::new();
    source.push_str("// AUTO-GENERATED by build.rs from mpz-poly-proof-lifter.\n");
    source.push_str("// Do not edit; regenerate by changing the lifter or fixtures.\n\n");

    macro_rules! lift {
        ($def_name:literal, $fixture:path, $num_vars:literal) => {{
            let ir = trace_constraint::<Gf2_64, Gf2, _, $num_vars>(|ctx, vars| {
                $fixture(ctx, vars).map_err(|_| LifterError::NoConstraint)
            })
            .unwrap_or_else(|e| panic!("lifter failed on {}: {e}", $def_name));
            let prover_name = format!("{}Kernel", $def_name);
            let verifier_name = format!("{}VerifierKernel", $def_name);
            source.push_str(&emit_prover(&prover_name, &ir, &paths));
            source.push_str("\n\n");
            source.push_str(&emit_verifier(&verifier_name, &ir, &paths));
            source.push_str("\n\n");
            source.push_str(&emit_constraint_def(
                $def_name,
                &prover_name,
                &verifier_name,
                &ir,
                &paths,
            ));
            source.push_str("\n\n");
        }};
    }

    lift!("GenCarryGenerate", fixtures::carry_generate, 5);
    lift!("GenCarryChain", fixtures::carry_chain, 4);
    lift!("GenWriteBack", fixtures::write_back, 13);
    lift!("GenWriteBackBit0", fixtures::write_back_bit0, 14);
    lift!("GenAddrBaseMux", fixtures::addr_base_mux, 6);
    lift!("GenAddrIndexMux", fixtures::addr_index_mux, 4);
    lift!("GenMulBitExtraction", fixtures::mul_bit_extraction, 38);
    lift!("GenMulForce", fixtures::mul_force, 3);
    lift!("GenAccMux", fixtures::acc_mux, 6);
    lift!("GenPcMux", fixtures::pc_mux, 8);
    lift!("GenSpMux", fixtures::sp_mux, 6);
    lift!("GenFpMux", fixtures::fp_mux, 4);

    fs::write(&dest, source).expect("failed to write gen_kernels.rs");

    println!("cargo:rerun-if-changed=build.rs");
}
