//! Do NOT edit this file manually!
//!
//! This module is automatically generated with the crate `lpn-estimator` using the binary
//! `estimator.rs`. If you want to make changes run the estimator and replace this file
//! with the generated output.
use mpz_core::lpn::LpnParameters;
/// LPN parameters.
pub static LPN_PARAMS: &[LpnParameters] = &[
    LpnParameters {
        n: 405000usize,
        k: 24750usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 870598usize,
        k: 49500usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 1871463usize,
        k: 99000usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 4022958usize,
        k: 198000usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 8647891usize,
        k: 408000usize,
        t: 1200usize,
    },
];

