//! Do NOT edit this file manually!
//!
//! This module is automatically generated with the crate `lpn-estimator` using
//! the binary `estimator.rs`. If you want to make changes run the estimator and
//! replace this file with the generated output.
use mpz_core::lpn::LpnParameters;
/// LPN parameters.
pub static LPN_PARAMS: &[LpnParameters] = &[
    LpnParameters {
        n: 153600usize,
        k: 10210usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 307200usize,
        k: 19244usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 614400usize,
        k: 36279usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 1228800usize,
        k: 68399usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 2457600usize,
        k: 128965usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 4915200usize,
        k: 243175usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 9830400usize,
        k: 458531usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 19660800usize,
        k: 907849usize,
        t: 1200usize,
    },
];
