//! Do NOT edit this file manually!
//!
//! This module is automatically generated with the crate `lpn-estimator` using
//! the binary `estimator.rs`. If you want to make changes run the estimator and
//! replace this file with the generated output.
use mpz_core::lpn::LpnParameters;
/// LPN parameters.
pub static LPN_PARAMS: &[LpnParameters] = &[
    LpnParameters {
        n: 614400usize,
        k: 34814usize,
        t: 1200usize,
    },
    LpnParameters {
        n: 9830400usize,
        k: 462040usize,
        t: 1200usize,
    },
];
