//! Core building blocks for the designated-verifier zero-knowledge proof system.
//!
//! The protocol runs a boolean circuit between a [`Prover`] and a [`Verifier`].
//! Evaluating the circuit on each side records the information needed to prove
//! and check the computation. The prover then produces a [`Proof`] with
//! [`Prover::prove`], which the verifier checks with [`Verifier::verify`].
//!
//! The two parties drive circuit evaluation through the [`ProverExecute`] and
//! [`VerifierExecute`] handles obtained from [`Prover::execute`] and
//! [`Verifier::execute`]. A [`Commit`] carries the adjustment bits the prover
//! sends to the verifier so both sides agree on the values consumed during
//! evaluation.
//!
//! Errors surfaced by these operations are reported via [`Error`] and the
//! crate-wide [`Result`] alias.

mod check;
mod poly;
mod poly_check;
mod prover;
mod util;
mod verifier;
mod vope;

pub use poly::PolyContext;
pub use prover::{Prover, ProverExecute};
pub use verifier::{Verifier, VerifierExecute};

use mpz_core::bitvec::BitVec;
use mpz_fields::gf2_128::Gf2_128;

/// A specialized [`Result`](core::result::Result) type for this crate's operations.
///
/// Defaults the error type to [`Error`].
pub type Result<T, E = Error> = core::result::Result<T, E>;

pub(crate) const MAC_ZERO: Gf2_128 = Gf2_128::new(u128::from_le_bytes([
    146, 239, 91, 41, 80, 62, 197, 196, 204, 121, 176, 38, 171, 216, 63, 120,
]));

pub(crate) const MAC_ONE: Gf2_128 = Gf2_128::new(u128::from_le_bytes([
    219, 104, 26, 50, 91, 130, 201, 178, 144, 31, 95, 155, 206, 113, 5, 103,
]));

/// The prover's commitment to the values consumed during circuit evaluation.
///
/// Sent from the prover to the verifier so both sides agree on the adjustments
/// applied during evaluation.
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Commit {
    /// The adjustment bits, one per entry consumed in evaluation order.
    pub adjust: BitVec,
}

/// A zero-knowledge proof produced by the prover over an evaluated circuit.
///
/// Produced by [`Prover::prove`] and consumed by [`Verifier::verify`].
#[derive(Debug, Clone, serde::Serialize, serde::Deserialize)]
pub struct Proof {
    pub(crate) assertions: [u8; 32],
    pub(crate) u: Gf2_128,
    pub(crate) v: Gf2_128,
    /// Masked coefficients of the degree-`d` polynomial check, degrees
    /// `0 ..= d_max - 1`. Empty when no polynomial constraints were evaluated.
    pub(crate) coefficients: Vec<Gf2_128>,
}

/// The prover's degree-`d_max` VOPE correlation, masking the polynomial check.
///
/// `coeffs[h]` masks the accumulated `Δ^h` coefficient; one entry per degree
/// `0 ..= d_max - 1`. Generated by an external `ext-sVOLE` and consumed here.
#[derive(Debug, Clone)]
pub struct ProverVope {
    /// One mask coefficient per degree.
    pub coeffs: Vec<Gf2_128>,
}

/// The verifier's side of the polynomial-check VOPE correlation.
///
/// `sum = Σ_h coeffs[h]·Δ^h` for the prover's [`ProverVope`] coefficients.
#[derive(Debug, Clone, Copy)]
pub struct VerifierVope {
    /// Δ-weighted sum of the prover's mask coefficients.
    pub sum: Gf2_128,
}

/// An error returned by the prover or verifier.
///
/// Returned within the crate-wide [`Result`] alias. The underlying cause is
/// kept opaque; use the [`Display`](std::fmt::Display) representation for
/// diagnostics.
#[derive(Debug, thiserror::Error)]
#[error(transparent)]
pub struct Error(#[from] ErrorRepr);

impl Error {
    pub(crate) fn assert() -> Self {
        Self(ErrorRepr::Assert)
    }

    pub(crate) fn check() -> Self {
        Self(ErrorRepr::Check)
    }

    pub(crate) fn tape_len(name: &'static str, expected: usize, actual: usize) -> Self {
        Self(ErrorRepr::TapeLength {
            name,
            expected,
            actual,
        })
    }

    pub(crate) fn tape_unconsumed(consumed: usize, total: usize) -> Self {
        Self(ErrorRepr::TapeUnconsumed { consumed, total })
    }
}

#[derive(Debug, thiserror::Error)]
enum ErrorRepr {
    #[error("consistency check failed")]
    Check,
    #[error("witness assertion failed")]
    Assert,
    #[error("tape `{name}` length mismatch: expected {expected}, got {actual}")]
    TapeLength {
        name: &'static str,
        expected: usize,
        actual: usize,
    },
    #[error("circuit consumed {consumed} of {total} tape entries")]
    TapeUnconsumed { consumed: usize, total: usize },
}

#[cfg(test)]
mod tests {
    use itybity::ToBits;
    use mpz_circuits_new::{
        Context,
        sha256::{AND_PER_BLOCK, H0, compress},
    };
    use mpz_fields::{gf2::Gf2, gf2_128::Gf2_128};
    use rand::{Rng, SeedableRng, rngs::StdRng};

    use super::{
        Error, ErrorRepr, PolyContext, Prover, ProverVope, Result, Verifier, VerifierVope,
        util::set_lsb,
    };

    /// Empty polynomial VOPE — for triple-only circuits (`d_max = 0`).
    fn no_poly() -> (ProverVope, VerifierVope) {
        (
            ProverVope { coeffs: Vec::new() },
            VerifierVope {
                sum: Gf2_128::ZERO,
            },
        )
    }

    fn random_delta(rng: &mut StdRng) -> Gf2_128 {
        let mut d = Gf2_128::new(rng.random());
        set_lsb(&mut d, true);
        d
    }

    fn corr(rng: &mut StdRng, delta: Gf2_128) -> (bool, Gf2_128, Gf2_128) {
        let choice: bool = rng.random();
        let key = Gf2_128::new(rng.random());
        let mac = if choice { key + delta } else { key };
        (choice, mac, key)
    }

    fn input(rng: &mut StdRng, b: bool, delta: Gf2_128) -> (Gf2_128, Gf2_128) {
        let mut key = Gf2_128::new(rng.random());
        set_lsb(&mut key, false);
        let mac = if b { key + delta } else { key };
        (mac, key)
    }

    struct Inputs {
        delta: Gf2_128,
        msg_macs: [Gf2_128; 512],
        msg_keys: [Gf2_128; 512],
        state_macs: [Gf2_128; 256],
        state_keys: [Gf2_128; 256],
        gate_masks: Vec<bool>,
        gate_macs: Vec<Gf2_128>,
        gate_keys: Vec<Gf2_128>,
        vope_choices: [bool; 128],
        vope_ev: [Gf2_128; 128],
        vope_keys: [Gf2_128; 128],
        chi: [u8; 32],
    }

    fn inputs(seed: u64) -> Inputs {
        let mut rng = StdRng::seed_from_u64(seed);
        let delta = random_delta(&mut rng);
        let chi: [u8; 32] = rng.random();

        let msg_words: [u32; 16] = core::array::from_fn(|_| rng.random());
        let msg_bits: Vec<bool> = msg_words.iter_lsb0().collect();
        let state_bits: Vec<bool> = H0.iter_lsb0().collect();

        let msg_pairs: Vec<(Gf2_128, Gf2_128)> = msg_bits
            .iter()
            .map(|&b| input(&mut rng, b, delta))
            .collect();
        let state_pairs: Vec<(Gf2_128, Gf2_128)> = state_bits
            .iter()
            .map(|&b| input(&mut rng, b, delta))
            .collect();
        let msg_macs: [Gf2_128; 512] = core::array::from_fn(|i| msg_pairs[i].0);
        let msg_keys: [Gf2_128; 512] = core::array::from_fn(|i| msg_pairs[i].1);
        let state_macs: [Gf2_128; 256] = core::array::from_fn(|i| state_pairs[i].0);
        let state_keys: [Gf2_128; 256] = core::array::from_fn(|i| state_pairs[i].1);

        let gates: Vec<_> = (0..AND_PER_BLOCK).map(|_| corr(&mut rng, delta)).collect();
        let gate_masks: Vec<bool> = gates.iter().map(|(c, _, _)| *c).collect();
        let gate_macs: Vec<Gf2_128> = gates.iter().map(|(_, m, _)| *m).collect();
        let gate_keys: Vec<Gf2_128> = gates.iter().map(|(_, _, k)| *k).collect();

        let vope: [(bool, Gf2_128, Gf2_128); 128] = core::array::from_fn(|_| corr(&mut rng, delta));
        let vope_choices: [bool; 128] = core::array::from_fn(|i| vope[i].0);
        let vope_ev: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].1);
        let vope_keys: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].2);

        Inputs {
            delta,
            msg_macs,
            msg_keys,
            state_macs,
            state_keys,
            gate_masks,
            gate_macs,
            gate_keys,
            vope_choices,
            vope_ev,
            vope_keys,
            chi,
        }
    }

    #[test]
    fn happy_path() {
        let i = inputs(1);

        let mut prover = Prover::new();
        let mut masks = i.gate_masks.clone();
        {
            let mut exec = prover.execute(&mut masks, &i.gate_macs).unwrap();
            let _ = compress(&mut exec, i.msg_macs, i.state_macs);
            exec.finish().unwrap();
        }
        let proof = prover.prove(i.chi, &i.vope_choices, &i.vope_ev, &no_poly().0);

        let mut verifier = Verifier::new(i.delta);
        {
            let mut exec = verifier.execute(&i.gate_keys, &masks).unwrap();
            let _ = compress(&mut exec, i.msg_keys, i.state_keys);
            exec.finish().unwrap();
        }
        verifier.verify(i.chi, &i.vope_keys, &no_poly().1, proof).unwrap();
    }

    #[test]
    fn corrupted_triple_rejected() {
        // Run an honest prover; corrupt a verifier gate key before
        // its execute pass so its triple's z doesn't match.
        let mut i = inputs(2);

        let mut prover = Prover::new();
        let mut masks = i.gate_masks.clone();
        {
            let mut exec = prover.execute(&mut masks, &i.gate_macs).unwrap();
            let _ = compress(&mut exec, i.msg_macs, i.state_macs);
            exec.finish().unwrap();
        }
        let proof = prover.prove(i.chi, &i.vope_choices, &i.vope_ev, &no_poly().0);

        i.gate_keys[0] = i.gate_keys[0] + Gf2_128::new(0xdead_beef_dead_beef_dead_beef_dead_beef);

        let mut verifier = Verifier::new(i.delta);
        {
            let mut exec = verifier.execute(&i.gate_keys, &masks).unwrap();
            let _ = compress(&mut exec, i.msg_keys, i.state_keys);
            exec.finish().unwrap();
        }
        let Error(repr) = verifier.verify(i.chi, &i.vope_keys, &no_poly().1, proof).unwrap_err();
        assert!(matches!(repr, ErrorRepr::Check));
    }

    #[test]
    fn corrupted_assertion_rejected() {
        // sha256-compress doesn't call `assert`, so flipping a bit
        // in the proof's assertions hash makes it differ from the
        // verifier's expected (empty) hash.
        let i = inputs(3);

        let mut prover = Prover::new();
        let mut masks = i.gate_masks.clone();
        {
            let mut exec = prover.execute(&mut masks, &i.gate_macs).unwrap();
            let _ = compress(&mut exec, i.msg_macs, i.state_macs);
            exec.finish().unwrap();
        }
        let mut proof = prover.prove(i.chi, &i.vope_choices, &i.vope_ev, &no_poly().0);
        proof.assertions[0] ^= 1;

        let mut verifier = Verifier::new(i.delta);
        {
            let mut exec = verifier.execute(&i.gate_keys, &masks).unwrap();
            let _ = compress(&mut exec, i.msg_keys, i.state_keys);
            exec.finish().unwrap();
        }
        let Error(repr) = verifier.verify(i.chi, &i.vope_keys, &no_poly().1, proof).unwrap_err();
        assert!(matches!(repr, ErrorRepr::Assert));
    }

    #[test]
    fn verifier_tape_length_mismatch_rejected() {
        let i = inputs(4);

        // Adjust slice one bit shorter than the key tape.
        let bad_adjust = vec![false; i.gate_keys.len() - 1];

        let mut verifier = Verifier::new(i.delta);
        let Error(repr) = verifier
            .execute(&i.gate_keys, &bad_adjust)
            .unwrap_err();
        assert!(matches!(repr, ErrorRepr::TapeLength { .. }));
    }

    #[test]
    fn wrong_vope_keys_rejected() {
        let mut i = inputs(5);

        let mut prover = Prover::new();
        let mut masks = i.gate_masks.clone();
        {
            let mut exec = prover.execute(&mut masks, &i.gate_macs).unwrap();
            let _ = compress(&mut exec, i.msg_macs, i.state_macs);
            exec.finish().unwrap();
        }
        let proof = prover.prove(i.chi, &i.vope_choices, &i.vope_ev, &no_poly().0);

        let mut verifier = Verifier::new(i.delta);
        {
            let mut exec = verifier.execute(&i.gate_keys, &masks).unwrap();
            let _ = compress(&mut exec, i.msg_keys, i.state_keys);
            exec.finish().unwrap();
        }
        i.vope_keys[0] = i.vope_keys[0] + Gf2_128::new(0xfeed_face_feed_face_feed_face_feed_face);
        let Error(repr) = verifier.verify(i.chi, &i.vope_keys, &no_poly().1, proof).unwrap_err();
        assert!(matches!(repr, ErrorRepr::Check));
    }

    #[test]
    fn prover_tape_length_mismatch_rejected() {
        let mut prover = Prover::new();
        let mut masks: Vec<bool> = Vec::new();
        let macs = [Gf2_128::new(0)];
        let Error(repr) = prover.execute(&mut masks, &macs).unwrap_err();
        assert!(matches!(repr, ErrorRepr::TapeLength { .. }));
    }

    #[test]
    fn check_depends_on_chi() {
        // Two runs that differ only in the challenge produce different
        // (u, v) — confirms the check actually consumes χ.
        let i = inputs(7);

        let run = |chi: [u8; 32]| {
            let mut prover = Prover::new();
            let mut masks = i.gate_masks.clone();
            {
                let mut exec = prover.execute(&mut masks, &i.gate_macs).unwrap();
                let _ = compress(&mut exec, i.msg_macs, i.state_macs);
                exec.finish().unwrap();
            }
            prover.prove(chi, &i.vope_choices, &i.vope_ev, &no_poly().0)
        };

        let a = run([1u8; 32]);
        let b = run([2u8; 32]);
        assert_ne!((a.u, a.v), (b.u, b.v));
    }

    #[test]
    fn assert_eq_round_trip() {
        // Two input wires committed to the same bit; assert_eq must
        // pass on both sides and the proof must verify.
        let mut rng = StdRng::seed_from_u64(8);
        let delta = random_delta(&mut rng);
        let (mac_a, key_a) = input(&mut rng, true, delta);
        let (mac_b, key_b) = input(&mut rng, true, delta);

        let mut gate_masks: Vec<bool> = Vec::new();
        let gate_macs: Vec<Gf2_128> = Vec::new();
        let gate_keys: Vec<Gf2_128> = Vec::new();
        let vope: [(bool, Gf2_128, Gf2_128); 128] = core::array::from_fn(|_| corr(&mut rng, delta));
        let vope_choices: [bool; 128] = core::array::from_fn(|i| vope[i].0);
        let vope_ev: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].1);
        let vope_keys: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].2);
        let chi: [u8; 32] = rng.random();

        let mut prover = Prover::new();
        {
            let mut exec = prover.execute(&mut gate_masks, &gate_macs).unwrap();
            exec.assert_eq(mac_a, mac_b).unwrap();
            exec.finish().unwrap();
        }
        let proof = prover.prove(chi, &vope_choices, &vope_ev, &no_poly().0);

        let mut verifier = Verifier::new(delta);
        {
            let mut exec = verifier.execute(&gate_keys, &gate_masks).unwrap();
            exec.assert_eq(key_a, key_b).unwrap();
            exec.finish().unwrap();
        }
        verifier.verify(chi, &vope_keys, &no_poly().1, proof).unwrap();
    }

    #[test]
    fn assert_eq_unequal_returns_err_on_prover() {
        // Prover-side `assert_eq` on two wires committed to
        // different bits short-circuits with `Error::Assert` (the
        // `got != expected` check inside `assert_const`).
        let mut rng = StdRng::seed_from_u64(9);
        let delta = random_delta(&mut rng);
        let (mac_a, _) = input(&mut rng, true, delta);
        let (mac_b, _) = input(&mut rng, false, delta);

        let mut gate_masks: Vec<bool> = Vec::new();
        let gate_macs: Vec<Gf2_128> = Vec::new();

        let mut prover = Prover::new();
        let mut exec = prover.execute(&mut gate_masks, &gate_macs).unwrap();
        let Error(repr) = exec.assert_eq(mac_a, mac_b).unwrap_err();
        assert!(matches!(repr, ErrorRepr::Assert));
    }

    #[test]
    fn assert_eq_dishonest_prover_rejected() {
        // Dishonest prover tries to assert equality between two
        // unequal wires by skipping the local `assert_eq` call (so
        // its `assertions` hash differs from the verifier's
        // expectation, since the verifier still calls `assert_eq`).
        let mut rng = StdRng::seed_from_u64(10);
        let delta = random_delta(&mut rng);
        let (_mac_a, key_a) = input(&mut rng, true, delta);
        let (_mac_b, key_b) = input(&mut rng, false, delta);

        let mut gate_masks: Vec<bool> = Vec::new();
        let gate_macs: Vec<Gf2_128> = Vec::new();
        let gate_keys: Vec<Gf2_128> = Vec::new();
        let vope: [(bool, Gf2_128, Gf2_128); 128] = core::array::from_fn(|_| corr(&mut rng, delta));
        let vope_choices: [bool; 128] = core::array::from_fn(|i| vope[i].0);
        let vope_ev: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].1);
        let vope_keys: [Gf2_128; 128] = core::array::from_fn(|i| vope[i].2);
        let chi: [u8; 32] = rng.random();

        // Prover skips the assertion (simulating a malicious party).
        let mut prover = Prover::new();
        {
            let exec = prover.execute(&mut gate_masks, &gate_macs).unwrap();
            // No assert_eq call here.
            exec.finish().unwrap();
        }
        let proof = prover.prove(chi, &vope_choices, &vope_ev, &no_poly().0);

        // Verifier honestly performs the assertion.
        let mut verifier = Verifier::new(delta);
        {
            let mut exec = verifier.execute(&gate_keys, &gate_masks).unwrap();
            exec.assert_eq(key_a, key_b).unwrap();
            exec.finish().unwrap();
        }
        let Error(repr) = verifier.verify(chi, &vope_keys, &no_poly().1, proof).unwrap_err();
        assert!(matches!(repr, ErrorRepr::Assert));
    }

    /// A degree-`d_max` polynomial-check VOPE correlation, mocked from `delta`.
    fn mock_poly_vope(
        d_max: usize,
        delta: Gf2_128,
        rng: &mut StdRng,
    ) -> (ProverVope, VerifierVope) {
        let coeffs: Vec<Gf2_128> = (0..d_max).map(|_| Gf2_128::new(rng.random())).collect();
        let mut sum = Gf2_128::ZERO;
        let mut p = Gf2_128::ONE;
        for &c in &coeffs {
            sum = sum + c * p;
            p = p * delta;
        }
        (ProverVope { coeffs }, VerifierVope { sum })
    }

    /// Polynomial part of the composite circuit, shared by both sides: a
    /// degree-3 `assert_zero` (`a·b·c + p·c == 0`, satisfied since `p = a·b`)
    /// and a degree-2 `materialize` (`out = a·c`). `d_max = 3`.
    fn poly_part<C: PolyContext<Field = Gf2>>(
        ctx: &mut C,
        a: C::Wire,
        b: C::Wire,
        c: C::Wire,
        p: C::Wire,
    ) -> Result<C::Wire>
    where
        C::Error: Into<Error>,
    {
        let (ae, be, ce, pe) = (ctx.lift(a), ctx.lift(b), ctx.lift(c), ctx.lift(p));
        ctx.assert_zero(ae * be * ce + pe * ce).map_err(Into::into)?;
        Ok(ctx.materialize(ae * ce))
    }

    /// One AND gate (triple path) plus a degree-3 `assert_zero` and degree-2
    /// `materialize` (poly path), all in one `execute` walk, verifies.
    #[test]
    fn composite_circuit_verifies() {
        let mut rng = StdRng::seed_from_u64(0x_C0_DE);
        let delta = random_delta(&mut rng);
        let chi: [u8; 32] = rng.random();
        // 5 commits: inputs a, b, c; the AND gate p; the materialized output.
        let tape: Vec<(bool, Gf2_128, Gf2_128)> =
            (0..5).map(|_| corr(&mut rng, delta)).collect();
        let macs: Vec<Gf2_128> = tape.iter().map(|t| t.1).collect();
        let keys: Vec<Gf2_128> = tape.iter().map(|t| t.2).collect();
        let (pv, vv) = mock_poly_vope(3, delta, &mut rng);

        let mut prover = Prover::new();
        let mut masks: Vec<bool> = tape.iter().map(|t| t.0).collect();
        {
            let mut exec = prover.execute(&mut masks, &macs).unwrap();
            let a = exec.input(true);
            let b = exec.input(true);
            let c = exec.input(false);
            let p = Context::mul(&mut exec, a, b);
            let _ = poly_part(&mut exec, a, b, c, p).unwrap();
            exec.finish().unwrap();
        }
        let proof = prover.prove(chi, &[false; 128], &[Gf2_128::ZERO; 128], &pv);

        let mut verifier = Verifier::new(delta);
        {
            let mut exec = verifier.execute(&keys, &masks).unwrap();
            let a = exec.input();
            let b = exec.input();
            let c = exec.input();
            let p = Context::mul(&mut exec, a, b);
            let _ = poly_part(&mut exec, a, b, c, p).unwrap();
            exec.finish().unwrap();
        }
        verifier
            .verify(chi, &[Gf2_128::ZERO; 128], &vv, proof)
            .unwrap();
    }

    /// Corrupting a sent polynomial coefficient makes the poly check fail.
    #[test]
    fn composite_corrupted_coefficient_rejected() {
        let mut rng = StdRng::seed_from_u64(0x_BAD_C0);
        let delta = random_delta(&mut rng);
        let chi: [u8; 32] = rng.random();
        let tape: Vec<(bool, Gf2_128, Gf2_128)> =
            (0..5).map(|_| corr(&mut rng, delta)).collect();
        let macs: Vec<Gf2_128> = tape.iter().map(|t| t.1).collect();
        let keys: Vec<Gf2_128> = tape.iter().map(|t| t.2).collect();
        let (pv, vv) = mock_poly_vope(3, delta, &mut rng);

        let mut prover = Prover::new();
        let mut masks: Vec<bool> = tape.iter().map(|t| t.0).collect();
        {
            let mut exec = prover.execute(&mut masks, &macs).unwrap();
            let a = exec.input(true);
            let b = exec.input(false);
            let c = exec.input(true);
            let p = Context::mul(&mut exec, a, b);
            let _ = poly_part(&mut exec, a, b, c, p).unwrap();
            exec.finish().unwrap();
        }
        let mut proof = prover.prove(chi, &[false; 128], &[Gf2_128::ZERO; 128], &pv);
        proof.coefficients[0] = proof.coefficients[0] + Gf2_128::ONE;

        let mut verifier = Verifier::new(delta);
        {
            let mut exec = verifier.execute(&keys, &masks).unwrap();
            let a = exec.input();
            let b = exec.input();
            let c = exec.input();
            let p = Context::mul(&mut exec, a, b);
            let _ = poly_part(&mut exec, a, b, c, p).unwrap();
            exec.finish().unwrap();
        }
        let Error(repr) = verifier
            .verify(chi, &[Gf2_128::ZERO; 128], &vv, proof)
            .unwrap_err();
        assert!(matches!(repr, ErrorRepr::Check));
    }
}
